version: 2
updates:
- package-ecosystem: bundler
  directory: "/healthcheck"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  # Ignore all update to ruby as this is handled by the ruby-updater workflow.
  - dependency-name: "ruby"
