FROM ruby:3.0.3-alpine

# Set up the radius configs. linux-headers and openssl-dev are needed for building Ruby.
RUN apk --no-cache add wpa_supplicant freeradius freeradius-rest freeradius-eap openssl make gcc libc-dev linux-headers openssl-dev \
 && mkdir -p /tmp/radiusd /etc/raddb \
 && openssl dhparam -out /etc/raddb/dh 1024
COPY radius /etc/raddb
