FROM python:3.11-alpine

VOLUME /etc/raddb/certs

RUN pip install awscli --upgrade

COPY scripts/split_pem.py /split_pem.py
COPY raddb.sh /raddb.sh
RUN chmod +x /raddb.sh

ENTRYPOINT ["/raddb.sh"]
CMD [ "date" ]
