FROM python:3-alpine
VOLUME /etc/raddb/certs
RUN wget "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" \
 && unzip awscli-bundle.zip \
 && rm awscli-bundle.zip \
 && ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws \
 && rm -r ./awscli-bundle
COPY raddb.sh /raddb.sh
RUN chmod +x /raddb.sh
ENTRYPOINT ["/raddb.sh"]
CMD [ "date" ]
