# frozen_string_literal: true

source "http://rubygems.org"
ruby File.read(".ruby-version").chomp

gem "puma"
gem "sqlite3", force_ruby_platform: true
gem "sequel"
gem "sinatra"
gem "rspec"
gem "rack-test"

group :test do
  gem "rubocop-govuk"
end
