# frozen_string_literal: true

source "http://rubygems.org"
ruby File.read(".ruby-version").chomp

gem "puma"
gem "sqlite3"
gem "sequel"
gem "sinatra"
gem "rspec"

group :test do
  gem "rubocop-govuk"
end
